import { defineField, defineType } from "sanity";

export const homepage = defineType({
  name: "homepage",
  title: "Homepage",
  type: "document",
  fields: [
    defineField({
      name: "heroSection",
      title: "Hero Section",
      type: "object",
      fields: [
        defineField({ name: "badgeText", title: "Badge Text", type: "string" }),
        defineField({ name: "title", title: "Title", type: "string" }),
        defineField({ name: "subtitle", title: "Subtitle", type: "text" }),
        defineField({ name: "subtitleHighlight", title: "Subtitle Highlight", type: "string" }),
        defineField({ name: "primaryButtonText", title: "Primary Button Text", type: "string" }),
        defineField({ name: "primaryButtonLink", title: "Primary Button Link", type: "string" }),
        defineField({ name: "secondaryButtonText", title: "Secondary Button Text", type: "string" }),
        defineField({ name: "secondaryButtonLink", title: "Secondary Button Link", type: "string" }),
        defineField({ name: "heroImage", title: "Hero Image", type: "imageWithAlt" }),
        defineField({ name: "googleRating", title: "Google Rating", type: "number" }),
        defineField({ name: "googleReviewCount", title: "Google Review Count", type: "string" }),
        defineField({
          name: "trustBadges",
          title: "Trust Badges",
          type: "array",
          of: [{ type: "string" }],
        }),
        defineField({
          name: "stats",
          title: "Stats",
          type: "array",
          of: [{ type: "statItem" }],
        }),
        defineField({ name: "consultationFormTitle", title: "Consultation Form Title", type: "string" }),
      ],
    }),
    defineField({
      name: "trustBar",
      title: "Trust Bar",
      type: "object",
      fields: [
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "description", title: "Description", type: "text" }),
        defineField({
          name: "badges",
          title: "Badges",
          type: "array",
          of: [{ type: "badgeItem" }],
        }),
      ],
    }),
    defineField({
      name: "servicesSection",
      title: "Services Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({
          name: "services",
          title: "Services",
          type: "array",
          of: [{ type: "serviceCard" }],
        }),
      ],
    }),
    defineField({
      name: "ctaBanner",
      title: "CTA Banner",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "backgroundImage", title: "Background Image", type: "imageWithAlt" }),
        defineField({ name: "title", title: "Title", type: "string" }),
        defineField({ name: "subtitle", title: "Subtitle", type: "text" }),
        defineField({ name: "buttonText", title: "Button Text", type: "string" }),
        defineField({ name: "buttonLink", title: "Button Link", type: "string" }),
        defineField({ name: "footerNote", title: "Footer Note", type: "string" }),
      ],
    }),
    defineField({
      name: "whyHomeCare",
      title: "Why Home Care Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "description", title: "Description", type: "text" }),
        defineField({ name: "image", title: "Image", type: "imageWithAlt" }),
        defineField({ name: "overlayTitle", title: "Overlay Title", type: "string" }),
        defineField({ name: "overlayText", title: "Overlay Text", type: "string" }),
        defineField({
          name: "benefits",
          title: "Benefits",
          type: "array",
          of: [{ type: "benefitItem" }],
        }),
      ],
    }),
    defineField({
      name: "aboutSection",
      title: "About Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "description", title: "Description", type: "text" }),
        defineField({ name: "image", title: "Image", type: "imageWithAlt" }),
        defineField({
          name: "features",
          title: "Features",
          type: "array",
          of: [{ type: "featureItem" }],
        }),
        defineField({ name: "buttonText", title: "Button Text", type: "string" }),
        defineField({ name: "buttonLink", title: "Button Link", type: "string" }),
      ],
    }),
    defineField({
      name: "processSection",
      title: "Process Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({
          name: "steps",
          title: "Steps",
          type: "array",
          of: [{ type: "processStep" }],
        }),
        defineField({ name: "calloutTitle", title: "Callout Title", type: "string" }),
        defineField({ name: "calloutDescription", title: "Callout Description", type: "text" }),
      ],
    }),
    defineField({
      name: "pricingSection",
      title: "Pricing Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({
          name: "plans",
          title: "Plans",
          type: "array",
          of: [{ type: "pricingPlan" }],
        }),
        defineField({ name: "footerNote", title: "Footer Note", type: "string" }),
        defineField({ name: "footerLinkText", title: "Footer Link Text", type: "string" }),
        defineField({ name: "footerLink", title: "Footer Link", type: "string" }),
      ],
    }),
    defineField({
      name: "comparisonSection",
      title: "Comparison Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({ name: "leftTitle", title: "Left Title", type: "string" }),
        defineField({ name: "rightTitle", title: "Right Title", type: "string" }),
        defineField({
          name: "leftItems",
          title: "Left Items",
          type: "array",
          of: [{ type: "string" }],
        }),
        defineField({
          name: "rightItems",
          title: "Right Items",
          type: "array",
          of: [{ type: "string" }],
        }),
        defineField({ name: "leftImage", title: "Left Image", type: "imageWithAlt" }),
        defineField({ name: "rightImage", title: "Right Image", type: "imageWithAlt" }),
      ],
    }),
    defineField({
      name: "serviceAreasSection",
      title: "Service Areas Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({
          name: "stats",
          title: "Stats",
          type: "array",
          of: [{ type: "statItem" }],
        }),
        defineField({
          name: "areas",
          title: "Areas",
          type: "array",
          of: [{ type: "areaItem" }],
        }),
        defineField({ name: "officeLabel", title: "Office Label", type: "string" }),
        defineField({ name: "ctaText", title: "CTA Text", type: "string" }),
        defineField({ name: "buttonText", title: "Button Text", type: "string" }),
        defineField({ name: "buttonLink", title: "Button Link", type: "string" }),
      ],
    }),
    defineField({
      name: "testimonialsSection",
      title: "Testimonials Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
      ],
    }),
    defineField({
      name: "faqSection",
      title: "FAQ Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({
          name: "faqs",
          title: "FAQs",
          type: "array",
          of: [{ type: "faqItem" }],
        }),
        defineField({ name: "ctaText", title: "CTA Text", type: "string" }),
      ],
    }),
    defineField({
      name: "contactSection",
      title: "Contact Section",
      type: "object",
      fields: [
        defineField({ name: "badge", title: "Badge", type: "string" }),
        defineField({ name: "heading", title: "Heading", type: "string" }),
        defineField({ name: "subHeading", title: "Sub Heading", type: "text" }),
        defineField({ name: "image", title: "Main Image", type: "imageWithAlt" }),
        defineField({ name: "secondaryImage", title: "Secondary Image", type: "imageWithAlt" }),
        defineField({ name: "phone", title: "Phone", type: "string" }),
        defineField({ name: "whatsapp", title: "WhatsApp", type: "string" }),
        defineField({ name: "formTitle", title: "Form Title", type: "string" }),
        defineField({ name: "submitButtonText", title: "Submit Button Text", type: "string" }),
      ],
    }),
  ],
});
